"""empty message

Revision ID: 0bba063999eb
Revises: 1390d3897bfa
Create Date: 2022-03-26 10:30:46.185143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bba063999eb'
down_revision = '1390d3897bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentPostNotification',
    sa.Column('not_id', sa.Integer(), nullable=True),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['not_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['posts_id'], ['post.id'], )
    )
    op.add_column('notification', sa.Column('comment_post_author_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'comment_post_author_id')
    op.drop_table('commentPostNotification')
    # ### end Alembic commands ###
