"""empty message

Revision ID: 116ad6426094
Revises: 064b5c2f72af
Create Date: 2021-12-14 00:53:50.659957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116ad6426094'
down_revision = '064b5c2f72af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_token', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=32), nullable=True))
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
