"""empty message

Revision ID: 1390d3897bfa
Revises: 68e9375fc59e
Create Date: 2022-03-26 07:54:19.165159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1390d3897bfa'
down_revision = '68e9375fc59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followNotification',
    sa.Column('not_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['not_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['user.id'], )
    )
    op.add_column('notification', sa.Column('followed_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'followed_user_id')
    op.drop_table('followNotification')
    # ### end Alembic commands ###
