"""add not interested and reported posts table

Revision ID: 17938133e2cf
Revises: ed846a22e695
Create Date: 2022-01-18 16:52:51.244348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17938133e2cf'
down_revision = 'ed846a22e695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notInterested',
    sa.Column('post_id', sa.Boolean(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    op.create_table('reportedPost',
    sa.Column('post_id', sa.Boolean(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportedPost')
    op.drop_table('notInterested')
    # ### end Alembic commands ###
