"""empty message

Revision ID: 4fc06ecd786b
Revises: 505bfeacf50c
Create Date: 2022-02-15 19:45:52.708722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc06ecd786b'
down_revision = '505bfeacf50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('childcomment', 'parent')
    op.drop_column('comment', 'parent')
    op.add_column('post', sa.Column('liked_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'liked_by_user')
    op.add_column('comment', sa.Column('parent', sa.BOOLEAN(), nullable=True))
    op.add_column('childcomment', sa.Column('parent', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
