"""empty message

Revision ID: 68e9375fc59e
Revises: a9b81f4cb06e
Create Date: 2022-03-25 12:11:38.561572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e9375fc59e'
down_revision = 'a9b81f4cb06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('post_creator_id', sa.Integer(), nullable=True))
    op.add_column('notification', sa.Column('comment_creator_id', sa.Integer(), nullable=True))
    op.add_column('notification', sa.Column('child_comment_creator_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'child_comment_creator_id')
    op.drop_column('notification', 'comment_creator_id')
    op.drop_column('notification', 'post_creator_id')
    # ### end Alembic commands ###
