"""empty message

Revision ID: 7535f4e9d669
Revises: 42568b0438dc
Create Date: 2022-03-29 14:31:41.306921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7535f4e9d669'
down_revision = '42568b0438dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('followed_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'followed_by_user')
    # ### end Alembic commands ###
