"""empty message

Revision ID: 7e5b93cd4dc9
Revises: 0bba063999eb
Create Date: 2022-03-26 11:27:48.527290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5b93cd4dc9'
down_revision = '0bba063999eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentChildNotification',
    sa.Column('not_id', sa.Integer(), nullable=True),
    sa.Column('commnt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commnt_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['not_id'], ['notification.id'], )
    )
    op.add_column('notification', sa.Column('child_comment_author_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'child_comment_author_id')
    op.drop_table('commentChildNotification')
    # ### end Alembic commands ###
