"""empty message

Revision ID: 833b994de2f1
Revises: 7ccdabfdf26f
Create Date: 2022-01-26 02:49:02.227504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833b994de2f1'
down_revision = '7ccdabfdf26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likedComments',
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likedComments')
    # ### end Alembic commands ###
