"""empty message

Revision ID: 963813942cbd
Revises: 4fc06ecd786b
Create Date: 2022-02-16 09:43:23.077152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963813942cbd'
down_revision = '4fc06ecd786b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('childcomment', sa.Column('liked_by_user', sa.Boolean(), nullable=True))
    op.add_column('comment', sa.Column('liked_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'liked_by_user')
    op.drop_column('childcomment', 'liked_by_user')
    # ### end Alembic commands ###
