"""empty message

Revision ID: ec496ae50a27
Revises: 116ad6426094
Create Date: 2021-12-29 21:52:47.840209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec496ae50a27'
down_revision = '116ad6426094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.String(length=360), nullable=True))
    op.drop_column('post', 'ingredients')
    op.drop_column('post', 'recipe')
    op.drop_column('post', 'cookingSteps')
    op.drop_column('post', 'cookingTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cookingTime', sa.VARCHAR(length=10), nullable=True))
    op.add_column('post', sa.Column('cookingSteps', sa.VARCHAR(length=360), nullable=True))
    op.add_column('post', sa.Column('recipe', sa.VARCHAR(length=360), nullable=True))
    op.add_column('post', sa.Column('ingredients', sa.VARCHAR(length=360), nullable=True))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###
